### ISSUE TITLE
No Sound

### ISSUE THREAD

**Issue by paken7620** [zaf/asterisk-mstts#1]
I am attempting to use this. I'm not sure what I'm missing, but the command goes out, asterisk says the script completed, yet nothing plays back and then the call just terminates. I've turned on debugging, but I still am not seeing any errors.

**Comment by luisdemarchi** [comment]
@zaf  Four years later, I ended up in the same problem. I changed the variable debug = 1, key = my-ms-token and I do not know where to see the logs. When I make the call or click on a number, the return of the visual log is immediate, that is, it would not give time to receive an audio file.

PS: The commands that were passed do not work in Asterisk 16.

Log:

>     -- Executing [s@my_ivr:2] Set("SIP/2002-00000004", "TIMEOUT(digit)=5") in new stack
>     -- Digit timeout set to 5.000
>     -- Executing [s@my_ivr:3] AGI("SIP/2002-00000004", "mstts.agi,"Welcome to my small interactive voice response menu.",en-US") in new stack
>     -- Launched AGI Script /var/lib/asterisk/agi-bin/mstts.agi
>        > 0x7f591402c400 -- Strict RTP qualifying stream type: audio
>        > 0x7f591402c400 -- Strict RTP switching source address to 187.112.180.219:4020
>     -- <SIP/2002-00000004>AGI Script mstts.agi completed, returning 0
>     -- Executing [s@my_ivr:4] AGI("SIP/2002-00000004", "mstts.agi,"Please dial a digit.",en-US,any") in new stack
>     -- Launched AGI Script /var/lib/asterisk/agi-bin/mstts.agi
>     -- <SIP/2002-00000004>AGI Script mstts.agi completed, returning 0
>     -- Executing [s@my_ivr:5] WaitExten("SIP/2002-00000004", "") in new stack
>        > 0x7f591402c400 -- Strict RTP learning complete - Locking on source address 187.112.180.219:4020
>     -- Timeout on SIP/2002-00000004, going to 't'
>     -- Executing [t@my_ivr:1] AGI("SIP/2002-00000004", "mstts.agi,"Request timed out.",en-US") in new stack
>     -- Launched AGI Script /var/lib/asterisk/agi-bin/mstts.agi
>     -- <SIP/2002-00000004>AGI Script mstts.agi completed, returning 0
>     -- Executing [t@my_ivr:2] Goto("SIP/2002-00000004", "s,start") in new stack
>     -- Goto (my_ivr,s,4)
>     -- Executing [s@my_ivr:4] AGI("SIP/2002-00000004", "mstts.agi,"Please dial a digit.",en-US,any") in new stack
>     -- Launched AGI Script /var/lib/asterisk/agi-bin/mstts.agi
>     -- <SIP/2002-00000004>AGI Script mstts.agi completed, returning 0
>     -- Executing [s@my_ivr:5] WaitExten("SIP/2002-00000004", "") in new stack
> Really destroying SIP dialog '5LhyTRK35xJcwmr--d7ks4qogYxMlDac' Method: BYE
> 
> <--- SIP read from UDP:187.112.180.219:60297 --->
> 
> <------------->
>     -- Executing [7@my_ivr:1] AGI("SIP/2002-00000004", "mstts.agi,"You just pressed 7. Try another one please.",en-US,any") in new stack
>     -- Launched AGI Script /var/lib/asterisk/agi-bin/mstts.agi
>     -- <SIP/2002-00000004>AGI Script mstts.agi completed, returning 0
>     -- Executing [7@my_ivr:2] WaitExten("SIP/2002-00000004", "") in new stack
>     -- Timeout on SIP/2002-00000004, going to 't'
>     -- Executing [t@my_ivr:1] AGI("SIP/2002-00000004", "mstts.agi,"Request timed out.",en-US") in new stack
>     -- Launched AGI Script /var/lib/asterisk/agi-bin/mstts.agi
>     -- <SIP/2002-00000004>AGI Script mstts.agi completed, returning 0
>     -- Executing [t@my_ivr:2] Goto("SIP/2002-00000004", "s,start") in new stack
>     -- Goto (my_ivr,s,4)
>     -- Executing [s@my_ivr:4] AGI("SIP/2002-00000004", "mstts.agi,"Please dial a digit.",en-US,any") in new stack
>     -- Launched AGI Script /var/lib/asterisk/agi-bin/mstts.agi
> 
> <--- SIP read from UDP:187.112.180.219:60297 --->
> BYE sip:9000@52.39.253.60:6595 SIP/2.0
> Via: SIP/2.0/UDP 192.168.25.9:60297;rport;branch=z9hG4bKPjhEz1-s9xe5c0YFMw3i1JwUMJQ0hueFf5
> Max-Forwards: 70
> From: "Luis" <sip:2002@52.39.253.60>;tag=24LIiqeui9xVF6IM8.r3hYpkf-MRFO53
> To: <sip:9000@52.39.253.60>;tag=as04dff269
> Call-ID: NiYwpH.Z24GaynTZR5C0GQWf0DbB4-tE
> CSeq: 29525 BYE
> User-Agent: Telephone 1.4
> Content-Length: 0
> 
> <------------->
> --- (9 headers 0 lines) ---
> Sending to 187.112.180.219:60297 (NAT)
> Scheduling destruction of SIP dialog 'NiYwpH.Z24GaynTZR5C0GQWf0DbB4-tE' in 16704 ms (Method: BYE)
> 
> <--- Transmitting (NAT) to 187.112.180.219:60297 --->
> SIP/2.0 200 OK
> Via: SIP/2.0/UDP 192.168.25.9:60297;branch=z9hG4bKPjhEz1-s9xe5c0YFMw3i1JwUMJQ0hueFf5;received=187.112.180.219;rport=60297
> From: "Luis" <sip:2002@52.39.253.60>;tag=24LIiqeui9xVF6IM8.r3hYpkf-MRFO53
> To: <sip:9000@52.39.253.60>;tag=as04dff269
> Call-ID: NiYwpH.Z24GaynTZR5C0GQWf0DbB4-tE
> CSeq: 29525 BYE
> Server: Asterisk PBX 16.1.1
> Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
> Supported: replaces, timer
> Content-Length: 0
> 
> 
> <------------>
>     -- <SIP/2002-00000004>AGI Script mstts.agi completed, returning 4
>   == Spawn extension (my_ivr, s, 4) exited non-zero on 'SIP/2002-00000004'
>     -- Executing [h@my_ivr:1] Hangup("SIP/2002-00000004", "") in new stack
>   == Spawn extension (my_ivr, h, 1) exited non-zero on 'SIP/2002-00000004'
> 
> <--- SIP read from UDP:187.112.180.219:60297 --->
> 
> <------------->
> Really destroying SIP dialog 'NiYwpH.Z24GaynTZR5C0GQWf0DbB4-tE' Method: BYE
> 
> <--- SIP read from UDP:187.112.180.219:60297 --->
> 
> <------------->
> Reliably Transmitting (NAT) to 187.112.180.219:60297:
> OPTIONS sip:2002@192.168.25.9:60297;ob SIP/2.0
> Via: SIP/2.0/UDP 52.39.253.60:6595;branch=z9hG4bK6d7761db;rport
> Max-Forwards: 70
> From: "asterisk" <sip:asterisk@52.39.253.60:6595>;tag=as4d7e3d0e
> To: <sip:2002@192.168.25.9:60297;ob>
> Contact: <sip:asterisk@52.39.253.60:6595>
> Call-ID: 327f7b4b4b653dcb0b8d15414498c5be@52.39.253.60:6595
> CSeq: 102 OPTIONS
> User-Agent: Asterisk PBX 16.1.1
> Date: Fri, 15 Feb 2019 00:42:55 GMT
> Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
> Supported: replaces, timer
> Content-Length: 0
> 
> 
> ---
> 
> <--- SIP read from UDP:187.112.180.219:60297 --->
> SIP/2.0 200 OK
> Via: SIP/2.0/UDP 52.39.253.60:6595;rport=6595;received=52.39.253.60;branch=z9hG4bK6d7761db
> Call-ID: 327f7b4b4b653dcb0b8d15414498c5be@52.39.253.60:6595
> From: "asterisk" <sip:asterisk@52.39.253.60>;tag=as4d7e3d0e
> To: <sip:2002@192.168.25.9;ob>;tag=z9hG4bK6d7761db
> CSeq: 102 OPTIONS
> Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS
> Accept: application/sdp, application/pidf+xml, application/xpidf+xml, application/simple-message-summary, message/sipfrag;version=2.0, application/im-iscomposing+xml, text/plain
> Supported: replaces, 100rel, timer, norefersub
> Allow-Events: presence, message-summary, refer
> User-Agent: Telephone 1.4
> Content-Length: 0
> 
> <------------->
> --- (12 headers 0 lines) ---
> Really destroying SIP dialog '327f7b4b4b653dcb0b8d15414498c5be@52.39.253.60:6595' Method: OPTIONS

**Comment by luisdemarchi** [comment]
I discovered the solution in the blind (no log). I was removing and putting modules. What was missing was to include this module:

load = format_sln.so
