### ISSUE TITLE
sox failed to process sound file

### ISSUE THREAD

**Issue by jeetzz** [zaf/asterisk-mstts#2]
Hi Zaf,

Sorry to bother you again. I thought of switching to MSTTS for time being, the AGI is working fine. However the CLI perl script keeps returning the following.

[root@local~]# /usr/bin/mstts-cli.pl -o hello.wav -l en -t "Hello world"
/usr/bin/sox: invalid option -- -
/usr/bin/sox: invalid option -- n
/usr/bin/sox: invalid option -- o
/usr/bin/sox: -r must be given a positive integer
sox failed to process sound file. at /usr/bin/mstts-cli.pl line 249.

Can you pls assist? Thanks in advance.

**Comment by zaf** [comment]
What is your sox version? The CLI script only works with sox 14 or newer. Unfortunately sox has a bad habit of changing its cli interface completely from time to time. The AGI script detects that and uses different flags for sox depending on the detected version, the CLI script is only compatible with version 14 for now.

**Comment by jeetzz** [comment]
Okay cool. I got 12.18.1 will upgrade it to 14.4.2 now, any side affects the new sox would have on googletts?
Also if you could confirm, is there a way to choose from voices in MSTTS?

**Comment by zaf** [comment]
Googletts and mstts share quite a lot of code, both handle sox the same way. Upgrading sox will not affect any of them, quite the contrary.
Have a look at the README file for the list of supported languages.
