### ISSUE TITLE
Failed to get Access Token. at ./mstts-cli.pl line 223.

### ISSUE THREAD

**Issue by mathisa** [zaf/asterisk-mstts#3]
Hi
I installed a brand new PBX from Elastix (Elastix 4.0) which is based on CentOS 7. When I use the Microsoft Translator, I get the error message below.

./mstts-cli.pl -o hello.mp3 -l en -t "Hello world"
Failed to get Access Token. at ./mstts-cli.pl line 223.
You must have a client ID from Azure Marketplace to use this script. at ./mstts-cli.pl line 223.

I have pre-filled the IS and Secret, yet its not picking it up. have you encountered the issue, or are the requirements different for Centos 7?

Your assistance is greatly appreciated.

Mathis Azubike

**Comment by zaf** [comment]
Can you please try to run the script in debug mode in order to get some more output about what fails and where?

**Comment by zaf** [comment]
Please make sure you have all the needed Perl modules in order to handle https requests. Check if perl-LWP-Protocol-https is installed.
